USE pjo261aosw03rt3y;

CREATE TABLE IF NOT EXISTS burgers (
  id INT AUTO_INCREMENT NOT NULL,
  burger_name VARCHAR(64) NOT NULL,
  devoured BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);